1.Write a Python Program to Add Two Matrices?

In [41]:
#using numpy library
import numpy as np
matA = np.array([[1,2,3],[2,4,3]])
matB = np.array([[1,2,0],[2,4,0]])
matC = matA + matB

In [43]:
matC

array([[2, 4, 3],
       [4, 8, 3]])

2. Write a Python Program to Multiply Two Matrices?

In [46]:
import numpy as np
matA = np.array([[1,2,3],[2,4,3]])
matB = np.array([[1,2,0],[2,4,0]])
matC = matA* matB

In [47]:
matC

array([[ 1,  4,  0],
       [ 4, 16,  0]])

Write a Python Program to Transpose a Matrix?

In [48]:
import numpy as np
matA = np.array([[1,2,3],[2,4,3]])
matA.T

array([[1, 2],
       [2, 4],
       [3, 3]])

Write a Python Program to Sort Words in Alphabetic Order?

In [108]:
def sort_aphabetically(sentence):
    word_list = sentence.split(' ')
    word_list.sort()
    return word_list

In [109]:
sort_aphabetically('haha maile k bhanna milxa yar aabui')

['aabui', 'bhanna', 'haha', 'k', 'maile', 'milxa', 'yar']

Write a Python Program to Remove Punctuation From a String?

In [116]:
def remove_punctuation(sentence):
    punctuation_removed = sentence.replace('.', '')
    return punctuation_removed

In [117]:
remove_punctuation('haha maile k bhanna milxa yar.... aabui')

'haha maile k bhanna milxa yar aabui'